#!/bin/sh
# prerm script for ldm-themes
#
# see: dh_installdeb(1)

set -e

case "$1" in
    remove|deconfigure|failed-upgrade)

        update-alternatives \
            --remove ldm-theme /usr/share/ldm/themes/mint

        update-alternatives \
            --remove text.plymouth /usr/share/plymouth/themes/mint-text/mint-text.plymouth

        update-alternatives \
            --remove default.plymouth /usr/share/plymouth/themes/mint-logo/mint-logo.plymouth
    ;;

    upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
