#!/bin/sh
# postinst script
# see: dh_installdeb(1)

set -e

update_background (){
    # Update the default BG date (to force a DE bg refresh on upgrade)
    if [ -e /usr/share/backgrounds/hamonikr/default_background.jpg ]
    then
        touch /usr/share/backgrounds/hamonikr/default_background.jpg
        echo "Updated timestamp for default background"
    fi
}

case "$1" in
    configure)

    update_background

    glib-compile-schemas /usr/share/glib-2.0/schemas

    update-alternatives \
        --install /usr/share/ldm/themes/default ldm-theme \
        /usr/share/ldm/themes/mint 80

    ;;
    abort-upgrade|abort-remove|abort-deconfigure)

    ;;
    triggered)

    update_background

    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
